spring:
  application:
    name: contact-api
  config:
    import: optional:file:./secrets.yml

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

app:
  cors:
    origin: ${APP_CORS_ORIGIN:http://localhost:4200}